# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9fb1d42b3d2ddd47bb9d8d582d356d2d70464123036f82705f368c45c174d7753a1e46e47a4f61886d4eddfb4078b3b29a4ab960c46f704ab36db0df59dbc74

test:
  secret_key_base: 7183a0832d3ec22994197636b0d28cff6b25b3d563065f1f3b8b95d02e014af84ed98e521d65c62065e667cb499d2954f351fcd63f913f4c0245e6547a0737be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
